const API = '/api';
const state = { data: {}, inFlight: false, lastUpdated: null, timers: [], memoryFilter: '', auditFilter: '' };
const $ = (id) => document.getElementById(id);
const na = (value, fallback = '--') => value === null || value === undefined || value === '' ? fallback : value;
const text = (value) => String(na(value)).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number = (value, digits = 2) => value === null || value === undefined ? '--' : Number(value).toLocaleString(undefined, { maximumFractionDigits: digits });
const money = (value) => value === null || value === undefined ? '--' : `${Number(value) < 0 ? '-' : ''}$${Math.abs(Number(value)).toLocaleString(undefined,{maximumFractionDigits:2})}`;
const stamp = (value) => value ? new Date(value).toLocaleString() : '--';
const emptyRow = (columns, message) => `<tr class="empty-row"><td colspan="${columns}">${text(message)}</td></tr>`;

async function request(path) { const response = await fetch(`${API}${path}`, { headers: { Accept: 'application/json' } }); if (!response.ok) throw new Error(`${path}: ${response.status}`); return response.json(); }
async function refresh() {
  if (state.inFlight || document.hidden) return; state.inFlight = true; $('refresh-status').textContent = 'Refreshing…';
  try { const [overview, market, brain, positions, memory, lab, risk, health, audit] = await Promise.all([
    request('/control/overview'), request('/control/live-market'), request('/control/ai-brain'), request('/control/positions'), request('/control/trade-memory'), request('/control/model-lab'), request('/control/risk-center'), request('/control/system-health'), request('/control/audit-log')
  ]); const [research, backtests] = await Promise.all([request('/control/research-data'), request('/control/backtest-runs')]); state.data = { overview, market, brain, positions, memory, lab, risk, health, audit, research, backtests }; state.lastUpdated = new Date(); render(); $('global-error').hidden = true; $('refresh-status').textContent = `Updated ${state.lastUpdated.toLocaleTimeString()}`;
  } catch (error) { $('global-error').textContent = `API unavailable: ${error.message}. Displayed values may be stale.`; $('global-error').hidden = false; $('refresh-status').textContent = 'API error'; }
  finally { state.inFlight = false; }
}
function statusClass(value) { return value === true || value === 'ok' || value === 'NORMAL' ? 'safe' : value === false ? 'danger' : 'muted'; }
function card(label, value, tone = '') { return `<article class="metric-card"><div class="metric-label">${text(label)}</div><div class="metric-value ${tone}">${text(value)}</div></article>`; }
function renderTop() { const { overview = {}, health = {} } = state.data; const mt5 = !!health.mt5; $('top-mt5').className=`status-pill ${mt5?'safe':'danger'}`; $('top-mt5').textContent=`● MT5 ${mt5?'CONNECTED':'DISCONNECTED'}`; $('top-mode').textContent=overview.mode || '--'; $('sidebar-mode').textContent=overview.mode || '--'; $('top-mode').classList.toggle('live', overview.mode === 'LIVE'); $('top-brain').textContent=`Brain: ${na(overview.active_model)}`; $('top-database').className=`status-pill ${health.database?'safe':'danger'}`; $('top-database').textContent=`DB: ${health.database?'ONLINE':'WARNING'}`; const stop=overview.risk_status === 'EMERGENCY_STOP'; $('top-emergency').className=`status-pill ${stop?'danger':'safe'}`; $('top-emergency').textContent=`Emergency: ${stop?'ACTIVE':'clear'}`; }
function renderOverview() { const o=state.data.overview||{}; const values=[['MT5 Status',o.mt5_status?'Connected':'Disconnected',o.mt5_status?'positive':'negative'],['Trading Mode',na(o.mode)],['Active Model',na(o.active_model)],['Balance',money(o.balance)],['Equity',money(o.equity)],['Margin',money(o.margin)],['Daily P&L',money(o.daily_pnl),Number(o.daily_pnl)>0?'positive':Number(o.daily_pnl)<0?'negative':''],['Open Exposure',money(o.open_exposure)],['Current Drawdown',o.drawdown===null?'--':`${number(o.drawdown*100)}%`,o.drawdown>0?'negative':''],['Risk Status',na(o.risk_status),o.risk_status==='NORMAL'?'positive':'negative']]; $('overview-cards').innerHTML=values.map(v=>card(...v)).join(''); const h=state.data.health||{}; $('overview-system').classList.remove('skeleton-list'); $('overview-system').innerHTML=[['System Status',h.status==='ok'?'HEALTHY':'WARNING'],['AI Status',state.data.brain?.active_brain?'ACTIVE':'NOT AVAILABLE'],['Risk Status',na(o.risk_status)],['Last Updated',state.lastUpdated?.toLocaleString()||'--']].map(([k,v])=>`<div class="status-row"><span>${text(k)}</span><strong>${text(v)}</strong></div>`).join(''); const audits=(state.data.audit||[]).slice(0,4); $('recent-activity').innerHTML=audits.length?audits.map(a=>`<div class="activity-row"><span>${text(a.action)}</span><small>${stamp(a.timestamp)}</small></div>`).join(''):'<div class="empty-state">No audit activity available.</div>'; const positions=state.data.positions||[]; $('recent-trades').innerHTML=positions.length?positions.slice(0,4).map(p=>`<div class="activity-row"><span>${text(p.symbol)} ${text(p.type||p.side||'--')}</span><small>${text(p.volume)}</small></div>`).join(''):'<div class="empty-state">No open positions.</div>'; }
function renderMarket() { const rows=state.data.market||[], h=state.data.health||{}; $('market-state').textContent=h.mt5?'Feed Connected':'MT5 Disconnected'; $('market-state').className=`status-pill ${h.mt5?'safe':'danger'}`; $('market-disconnected').hidden=!!h.mt5; $('market-table').innerHTML=rows.length?rows.map(r=>`<tr><td>${text(r.symbol)}</td><td>${number(r.bid,5)}</td><td>${number(r.ask,5)}</td><td>${number(r.spread,5)}</td><td>${text(r.timeframe)}</td><td>${text(r.regime)}</td><td>${number(r.volatility,3)}</td><td>${stamp(r.timestamp)}</td><td>${h.mt5?'CONNECTED':'DISCONNECTED'}</td></tr>`).join(''):emptyRow(9,h.mt5?'No live market observations available.':'MT5 DISCONNECTED'); }
const f1 = (value) => value == null ? '--' : Number(value).toFixed(4);
function evaluation(model) {
  if (!model) return '<article class="panel"><div class="empty-state">No persisted Brain-v1 evaluation available.</div></article>';
  const v=model.validation_metrics||{}, o=model.out_of_sample_metrics||{}, s=model.oos_simulation||{};
  const cls=(metric, label) => f1(metric.per_class?.[label]?.f1);
  const metrics=[['Validation macro F1',f1(v.macro_f1)],['OOS macro F1',f1(o.macro_f1)],['Validation LONG F1',cls(v,'LONG')],['Validation SHORT F1',cls(v,'SHORT')],['Validation NO_TRADE F1',cls(v,'NO_TRADE')],['OOS LONG F1',cls(o,'LONG')],['OOS SHORT F1',cls(o,'SHORT')],['OOS NO_TRADE F1',cls(o,'NO_TRADE')],['Confidence threshold',f1(model.confidence_policy?.threshold)]];
  const sim=s.run_id?`<p><strong>OFFLINE OOS SIMULATION TRADES</strong> · Run ${text(s.run_id)} · ${stamp(s.simulation_timestamp)} · Dataset ${text(s.dataset_version)} / ${text(s.dataset_hash)}</p><div class="metric-grid">${[['Predictions',number(s.prediction_count,0)],['LONG / SHORT / NO_TRADE',`${number(s.prediction_counts?.LONG,0)} / ${number(s.prediction_counts?.SHORT,0)} / ${number(s.prediction_counts?.NO_TRADE,0)}`],['Simulated trades',number(s.simulated_trade_count,0)],['Wins / losses',`${number(s.wins,0)} / ${number(s.losses,0)}`],['Gross P&L USD',money(s.gross_pnl_usd)],['Transaction costs USD',money(s.transaction_costs_usd)],['Slippage USD',money(s.slippage_usd)],['Net P&L USD',money(s.net_pnl_usd)],['Profit factor',number(s.profit_factor,4)],['Max drawdown',`${number((s.max_drawdown||0)*100,4)}%`],['RUNTIME PAPER TRADES',number(s.runtime_paper_trades,0)]].map(x=>card(...x)).join('')}</div><div class="table-wrap"><table><thead><tr><th>Symbol</th><th>OOS coverage</th><th>Predictions</th><th>LONG</th><th>SHORT</th><th>NO_TRADE</th><th>Trades</th><th>Wins</th><th>Losses</th><th>Net P&L USD</th><th>Profit factor</th><th>Drawdown</th></tr></thead><tbody>${Object.entries(s.per_symbol||{}).map(([symbol,r])=>`<tr><td>${text(symbol)}</td><td>${text(r.coverage_status)}</td><td>${number(r.prediction_count,0)}</td><td>${number(r.prediction_counts?.LONG,0)}</td><td>${number(r.prediction_counts?.SHORT,0)}</td><td>${number(r.prediction_counts?.NO_TRADE,0)}</td><td>${number(r.simulated_trade_count,0)}</td><td>${number(r.wins,0)}</td><td>${number(r.losses,0)}</td><td>${money(r.net_pnl_usd)}</td><td>${number(r.profit_factor,4)}</td><td>${number((r.max_drawdown||0)*100,4)}%</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-state">No persisted OOS trading simulation.</div>';
  return `<article class="panel"><div class="panel-head"><h2>${text(model.model_id)} · ${text(model.status)}</h2></div><p>Candidate research model; no execution connection.</p><div class="metric-grid">${metrics.map(x=>card(...x)).join('')}</div><h3>Feature importance</h3><div class="model-list">${(model.feature_importance||[]).map(([name,value])=>`<div class="model-row"><span>${text(name)}</span><strong>${number(value,4)}</strong></div>`).join('')||'<div class="empty-state">No persisted feature importance.</div>'}</div><h3>OOS trading evaluation</h3>${sim}</article>`;
}
function renderBrain() { const b=state.data.brain||{}, d=b.latest_decision||{}; $('brain-cards').innerHTML=[['Active Brain',na(b.active_brain)],['Model Status',na(b.model_status)],['Latest Decision',na(d.direction,'Not Available')],['Confidence',d.confidence===null||d.confidence===undefined?'--':`${number(d.confidence*100)}%`],['Feature Version',na(d.feature_version)],['Last Inference',stamp(d.timestamp)]].map(v=>card(...v)).join(''); const c=b.candidates||[]; $('candidate-models').innerHTML=c.length?c.map(x=>`<div class="model-row"><strong>${text(x.model_id)}</strong><span class="status-pill warn">${text(x.status)}</span></div>`).join(''):'<div class="empty-state">No candidate models.</div>'; $('brain-evaluation').innerHTML=evaluation(c.find(x=>x.model_id==='Brain-v1')); }
function renderPositions() { const rows=state.data.positions||[]; $('positions-table').innerHTML=rows.length?rows.map(p=>`<tr><td>${text(p.symbol)}</td><td>${text(p.side||p.type)}</td><td>${number(p.volume,3)}</td><td>${number(p.price_open||p.entry,5)}</td><td>${number(p.price_current||p.current_price,5)}</td><td>${number(p.sl,5)}</td><td>${number(p.tp,5)}</td><td>${money(p.profit||p.floating_pnl)}</td><td>${text(p.model_id||p.model)}</td><td>${text(p.strategy_id||p.strategy)}</td><td>${text(p.trade_id||p.ticket)}</td><td>${text(p.status||'OPEN')}</td></tr>`).join(''):emptyRow(12,'No open positions'); }
function renderMemory() { const filter=state.memoryFilter.toLowerCase(), rows=(state.data.memory||[]).filter(r=>JSON.stringify(r).toLowerCase().includes(filter)); $('memory-table').innerHTML=rows.length?rows.map(r=>{const o=r.outcome||{}; const risk=r.risk||{}; const rm=o.risk_amount||risk.risk_amount; return `<tr><td>${text(r.trade_id)}</td><td>${text(r.direction)}</td><td>${r.confidence==null?'--':`${number(r.confidence*100)}%`}</td><td>${text(r.regime)}</td><td>${number(o.entry_price,5)}</td><td>${number(o.exit_price,5)}</td><td>${money(o.pnl_after_costs)}</td><td>${rm&&o.pnl_after_costs!=null?number(o.pnl_after_costs/rm,2):'--'}</td><td>${number(r.mfe)}</td><td>${number(r.mae)}</td><td>${text(o.exit_reason)}</td><td>${text(r.model_version)}</td></tr>`}).join(''):emptyRow(12,'No trade-memory records match this filter.'); }
function renderModels() { const lab=state.data.lab||{}, models=lab.models||[], champion=lab.production_champion; $('model-champion').innerHTML=`<div class="metric-label">PRODUCTION CHAMPION</div><div class="metric-value positive">${text(champion?.model_id,'Not Available')}</div><small>${text(champion?.status,'No production model')}</small>`; const stages=['TRAINING','CANDIDATE','VALIDATING','PAPER','SHADOW','APPROVED','PRODUCTION','REJECTED','RETIRED']; $('model-lifecycle').innerHTML=stages.map(s=>`<span class="${champion?.status===s?'production':''}">${s}</span>`).join(''); $('model-table').innerHTML=models.length?models.map(m=>`<div class="model-row"><div><strong>${text(m.model_id)}</strong><small>Parent: ${text(m.parent_model)} · Feature: ${text(m.feature_version)}</small></div><span class="status-pill ${m.status==='PRODUCTION'?'safe':m.status==='REJECTED'?'danger':'warn'}">${text(m.status)}</span></div>`).join(''):'<div class="empty-state">No model registry records.</div>'; $('model-evaluation').innerHTML=evaluation(models.find(x=>x.model_id==='Brain-v1')); }
function renderRisk() { const r=state.data.risk||{}, e=r.emergency_stop||{}; $('risk-summary').innerHTML=[['Emergency Stop',e.active?'ACTIVE':'CLEAR',e.active?'negative':'positive'],['Position Policy',na(e.position_policy)],['Risk Events',(r.risk_events||[]).length],['Relevant Alerts',(r.alerts||[]).length]].map(v=>card(...v)).join(''); const events=r.risk_events||[]; $('risk-events').innerHTML=events.length?events.map(x=>`<div class="activity-row"><span>${text(x.action)}</span><small>${stamp(x.timestamp)}</small></div>`).join(''):'<div class="empty-state">No recorded risk events.</div>'; }
function renderHealth() { const h=state.data.health||{}; const items=[['API',h.status==='ok'],['Database',h.database],['MT5',h.mt5],['Market Feed',!h.data_feed_stale],['AI Inference',h.ai_inference],['Execution Engine',h.execution_engine],['Risk Engine',h.risk_engine],['Background Workers',h.background_workers],['Last Tick',h.last_successful_tick],['Execution Latency',h.execution_latency],['Inference Latency',h.inference_latency]]; $('health-grid').innerHTML=items.map(([label,value])=>{const unavailable=value===undefined||value===null||value==='external_orchestrator_required'; const ok=value===true||value==='ok'; const cls=ok?'healthy':unavailable?'warning':'disconnected'; const status=ok?'HEALTHY':unavailable?(value==='external_orchestrator_required'?'Not Available':'Not Available'):'DISCONNECTED'; return `<article class="health-item ${cls}"><span>${text(label)}</span><strong>${text(status)}</strong><small>${label==='Last Tick'?stamp(value):''}</small></article>`}).join(''); }
function renderAudit() { const filter=state.auditFilter.toLowerCase(), rows=(state.data.audit||[]).filter(a=>JSON.stringify(a).toLowerCase().includes(filter)); $('audit-table').innerHTML=rows.length?rows.map(a=>`<tr><td>${stamp(a.timestamp)}</td><td>${text(a.action)}</td><td>${text((a.action||'').split('.')[0])}</td><td>${text(a.payload?.operator||a.session_id)}</td><td>${text(a.payload?.severity||'--')}</td><td title="${text(JSON.stringify(a.payload||{}))}">${text(JSON.stringify(a.payload||{})).slice(0,120)}</td></tr>`).join(''):emptyRow(6,'No audit records match this filter.'); }
function renderSettings() { const o=state.data.overview||{}, h=state.data.health||{}; $('settings-content').textContent=`Environment: ${o.environment||'--'}\nTrading Mode: ${o.mode||'--'}\nLIVE Execution: ${o.mode==='LIVE'?'Configured separately; verify backend controls.':'Disabled'}\nMT5: ${h.mt5?'Connected':'Disconnected'}\nDatabase: ${h.database?'Connected':'Warning'}\n\nThis interface is read-only for model/risk configuration. It does not place trades, promote models, or alter production weights.`; }
function renderResearch(){const r=state.data.research||{},a=r.aggregate||{},rows=r.coverage||[],d=r.dataset||{},examples=d.feature_snapshot_examples||[];$('research-cards').innerHTML=[['Data Pipeline',a.overall_status||'UNRESOLVED'],['Total Candles',number(r.total_candles,0)],['Symbols',(r.symbols||[]).join(', ')||'--'],['Timeframes',(r.timeframes||[]).join(', ')||'--'],['Quality',a.overall_status||'UNRESOLVED'],['Latest Ingestion',stamp(a.created_at)]].map(v=>card(...v)).join('');$('research-readiness').textContent=a.overall_status||'UNRESOLVED';$('dataset-governance').textContent=`Dataset: ${d.dataset_version||'--'}\nState: ${(d.dataset_state||'--').replace('_',' ')}\nFeatures: ${d.feature_count??'Not available'}\nFeature Snapshots: ${d.feature_snapshots??'Not available'}\nUsable / Excluded: ${d.usable_rows??'Not available'} / ${d.excluded_rows??'Not available'}\nSplits: Train ${d.train_rows??'--'} · Validation ${d.validation_rows??'--'} · OOS ${d.oos_rows??'--'}\nCoverage: ${stamp(d.source_start)} – ${stamp(d.source_end)}\nLeakage: ${d.leakage_status||'NOT RUN'}\nExecution: ${d.execution_timeframe||'--'}\nContext: ${(d.context_timeframes||[]).join(' / ')||'--'}\nAlignment: ${(d.alignment_policy||'--').replaceAll('_',' ')}\nContent Hash: ${d.content_hash||'Not available'}`;$('snapshot-examples').innerHTML=examples.length?examples.map(x=>{const v=x.values||{};return `<tr><td>${text(x.symbol)}</td><td>${stamp(x.decision_at)}</td><td>${text(x.split)}</td><td>${stamp(x.raw_data_cutoff)}</td><td>return ${number(v.return_1,5)} · ATR ${number(v.atr_14,5)} · RSI ${number(v.rsi_14,2)} · M15 ${text(v.m15_trend)}</td></tr>`}).join(''):emptyRow(5,'No active dataset snapshots.');$('research-table').innerHTML=rows.length?rows.map(x=>`<tr><td>${text(x.symbol)}</td><td>${text(x.timeframe)}</td><td>${number(x.count,0)}</td><td>${stamp(x.first)}</td><td>${stamp(x.last)}</td><td>${text(x.quality)}</td><td>${text((x.reason_codes||[]).join(', ')||'--')}</td><td>${number((x.details?.gaps||[]).filter(g=>g.classification!=='EXPECTED_MARKET_CLOSURE').length,0)}</td></tr>`).join(''):emptyRow(8,'No persisted research data.');}
function renderBacktests(){const rows=state.data.backtests||[];$('backtest-table').innerHTML=rows.length?rows.map(x=>{const m=x.metrics||{};return `<tr><td>${text(x.run_id)}</td><td>${text(x.strategy_version)}</td><td>${text(x.symbol)}</td><td>${text(x.timeframe)}</td><td>${number(m.trade_count,0)}</td><td>${money(m.net_pnl)}</td><td>${number(m.profit_factor,3)}</td><td>${m.maximum_drawdown==null?'--':`${number(m.maximum_drawdown*100,3)}%`}</td><td>${money(m.transaction_costs)}</td><td>${stamp(x.created_at)}</td><td>REPRODUCIBLE</td></tr>`}).join(''):emptyRow(11,'No persisted backtest runs.');}
function render(){renderTop();renderOverview();renderMarket();renderResearch();renderBacktests();renderBrain();renderPositions();renderMemory();renderModels();renderRisk();renderHealth();renderAudit();renderSettings();}
function activate(){const id=location.hash.slice(1)||'overview'; document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id)); document.querySelectorAll('.nav-link').forEach(a=>a.classList.toggle('active',a.dataset.section===id)); $('navigation').parentElement.classList.remove('open');}
function schedule(){state.timers.forEach(clearInterval);state.timers=[setInterval(refresh,3000)];}
document.getElementById('navigation').insertAdjacentHTML('beforeend','<a class="nav-link" href="#research-data" data-section="research-data">Research Data</a><a class="nav-link" href="#backtests" data-section="backtests">Backtests</a>'); $('refresh-now').addEventListener('click',refresh); $('memory-filter').addEventListener('input',e=>{state.memoryFilter=e.target.value;renderMemory()}); $('audit-filter').addEventListener('input',e=>{state.auditFilter=e.target.value;renderAudit()}); $('menu-toggle').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open')); window.addEventListener('hashchange',activate); document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});
$('emergency-stop').addEventListener('click',()=>$('emergency-dialog').showModal()); $('confirm-stop').addEventListener('click',async e=>{e.preventDefault();const operator=$('stop-operator').value,reason=$('stop-reason').value;if(!operator||!reason)return;try{const r=await fetch(`${API}/control/emergency-stop`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operator,reason})});if(!r.ok)throw new Error(`HTTP ${r.status}`);$('emergency-dialog').close();await refresh()}catch(err){$('global-error').textContent=`Emergency Stop request failed: ${err.message}`;$('global-error').hidden=false}});
activate(); schedule(); refresh();
