from typing import Protocol


class TradeMemory(Protocol):
    def record_decision(self, snapshot: dict) -> str: ...
    def record_execution(self, decision_id: str, execution: dict) -> None: ...
    def record_outcome(self, decision_id: str, outcome: dict) -> None: ...
